"""Invariants of reading the preset back.

Two programs meet in this file. calibrate decides what a profile costs and writes it
down; `vram` reads it and tells a person whether that model can be loaded right now. So
the strongest test here is the round trip: whatever the renderer wrote for a placement
is what this hands back for it. The rest are about a file that cannot be read at all,
which has to say so rather than answer with a number nobody computed.
"""

import unittest
from pathlib import Path

from cm import place
from cm.catalog import Loadable, parse
from cm.config import (DEFAULT_CUDA, DEFAULT_KEPT, DEFAULT_RUNTIME, Config,
                       ConfigError, Model)
from cm.machine import (Card, Core, Fitted, Machine, system_memory)
from cm.name import names
from cm.nonempty import NonEmpty
from cm.place import CacheType, ExpertsOnCpu, Settings, WholeCard
from cm.render import Placed, preset
from cm.serving import (DEFAULT_HOST, DEFAULT_IDLE, DEFAULT_PORT,
                        DEFAULT_RESIDENT, Serving)
from cm.units import Layers, Mib, Tokens
from one_card import LAYOUT, installed
from places import somewhere

MODELS = somewhere("models")

MACHINE = Machine(cards=installed(Card("NVIDIA GeForce RTX 5070 Ti", Mib(16303))),
                  ram=Mib(65407),
                  cores=tuple([Core(1, 2)] * 8 + [Core(0, 1)] * 8))

PRESET = f"""; Generated by calibrate on this machine. Do not edit.
;
; VRAM REQUIRED: 99999 MiB -- said up here, where it is about no section at all

version = 1

[*]
threads = 16

[gemma4-12b]
; VRAM REQUIRED: 10285 MiB of video memory, held from the moment this profile loads
model = {MODELS / 'gemma.gguf'}
ctx-size = 262000

[qwen3.8-45k-q8]
; VRAM REQUIRED: 15276 MiB of video memory, held from the moment this profile loads
model = {MODELS / 'qwen.gguf'}
ctx-size = 45000
"""


def without(section: str) -> str:
    """The preset with one section's requirement struck out."""
    kept = []
    inside = False
    for line in PRESET.splitlines():
        if line.startswith("["):
            inside = line == f"[{section}]"
        if not (inside and line.startswith("; VRAM REQUIRED")):
            kept.append(line)

    return "\n".join(kept)


MEMORY = system_memory(Fitted(), MACHINE, Mib(0))

# The one card of MACHINE, by the name llama.cpp gives it.
CARD = "CUDA0"


SERVING = Serving(host=DEFAULT_HOST, port=DEFAULT_PORT, resident=DEFAULT_RESIDENT,
                  idle=DEFAULT_IDLE, logs=somewhere("llama.cpp") / "logs")


def config() -> Config:
    return Config(model_root=MODELS,
                  cuda=DEFAULT_CUDA,
                  keep_releases=DEFAULT_KEPT,
                  preset_path=Path("llamacpp.models.ini"),
                  serving=SERVING,
                  reserve=Mib(1024),
                  min_ctx=Tokens(25000),
                  ample_ctx=Tokens(100000),
                  cache_ram=Fitted(),
                  runtime=DEFAULT_RUNTIME,
                  shared={},
                  models=(),
                  withheld=())


def settings(ctx, cache=CacheType.Q8_0, head=False, placement=None,
             spare=1024) -> Settings:
    return Settings(ctx=Tokens(ctx), cache=cache, head=head,
                    placement=placement or WholeCard(), spare=NonEmpty(Mib(spare)),
                    layout=LAYOUT)


def placed(key, *chosen) -> Placed:
    model = Model(key=key, path=MODELS / f"{key}.gguf",
                  vendor={}, allowed=place.EVERYTHING, manual=False)
    return Placed(model, names(key, chosen), Mib(0))


class WhatCalibrateWritesIsWhatVramReads(unittest.TestCase):
    """The one test that would catch the two of them drifting apart."""

    def test_every_placement_comes_back_with_the_room_it_was_given(self):
        written = preset(config(), MACHINE, MEMORY,
                         (placed("gemma4-12b", settings(262000, spare=6018)),
                          placed("ornith-1.0-35b",
                                 settings(131000, placement=ExpertsOnCpu(Layers(15)),
                                          spare=968))))

        self.assertEqual((Loadable("gemma4-12b", Mib(16303 - 6018)),
                          Loadable("ornith-1.0-35b", Mib(16303 - 968))),
                         parse(written, CARD))

    def test_every_profile_of_a_model_comes_back_under_its_own_name(self):
        written = preset(config(), MACHINE, MEMORY,
                         (placed("qwen3.8",
                                 settings(33000, head=True, spare=1001),
                                 settings(45000, spare=1027)),))

        self.assertEqual(["qwen3.8-33k-q8-mtp", "qwen3.8-45k-q8"],
                         [one.name for one in parse(written, CARD)])

    def test_the_shared_block_is_nothing_a_person_can_load(self):
        written = preset(config(), MACHINE, MEMORY, (placed("gemma4-12b", settings(262000)),))

        self.assertNotIn("*", [one.name for one in parse(written, CARD)])


class TheProfilesComeBackInTheOrderTheFileListsThem(unittest.TestCase):
    def test_the_order_is_the_files_own(self):
        self.assertEqual(["gemma4-12b", "qwen3.8-45k-q8"],
                         [one.name for one in parse(PRESET, CARD)])

    def test_the_figures_belong_to_the_sections_they_stand_in(self):
        self.assertEqual([Mib(10285), Mib(15276)],
                         [one.needs for one in parse(PRESET, CARD)])

    def test_what_stands_before_the_first_section_belongs_to_no_section(self):
        """A header that mentions the label is a header, not a profile."""
        self.assertNotIn(Mib(99999), [one.needs for one in parse(PRESET, CARD)])


class AFileThatCannotBeReadSaysSo(unittest.TestCase):
    def test_a_section_that_states_nothing_is_named(self):
        with self.assertRaises(ConfigError) as refused:
            parse(without("gemma4-12b"), CARD)

        self.assertIn("gemma4-12b", str(refused.exception))

    def test_silence_is_not_read_as_needing_nothing(self):
        """A profile needing nothing would be one that always fits, and every
        comparison downstream would wave it through."""
        with self.assertRaises(ConfigError):
            parse(without("qwen3.8-45k-q8"), CARD)

    def test_a_figure_that_is_not_a_number_is_refused(self):
        broken = PRESET.replace("10285 MiB", "plenty of MiB")

        with self.assertRaises(ConfigError):
            parse(broken, CARD)

    def test_a_preset_with_no_profiles_in_it_is_refused(self):
        with self.assertRaises(ConfigError):
            parse("version = 1\n\n[*]\nthreads = 16\n", CARD)

    def test_an_empty_file_is_refused(self):
        with self.assertRaises(ConfigError):
            parse("", CARD)


class TheRestOfTheFileIsNoneOfThisModulesBusiness(unittest.TestCase):
    def test_the_keys_a_section_carries_change_nothing(self):
        stripped = "\n".join(line for line in PRESET.splitlines()
                             if not line.startswith(("model =", "ctx-size")))

        self.assertEqual(parse(PRESET, CARD), parse(stripped, CARD))

    def test_indentation_and_blank_lines_change_nothing(self):
        spaced = "\n".join(f"   {line}   " if line else ""
                           for line in PRESET.splitlines())

        self.assertEqual(parse(PRESET, CARD), parse(spaced, CARD))

    def test_a_section_stating_it_twice_is_read_once(self):
        """Nothing writes that, and a list with one profile on it twice would be a
        person picking between two identical rows."""
        doubled = PRESET.replace(
            "; VRAM REQUIRED: 10285 MiB of video memory, held from the moment this "
            "profile loads",
            "; VRAM REQUIRED: 10285 MiB\n; VRAM REQUIRED: 10285 MiB")

        self.assertEqual(["gemma4-12b", "qwen3.8-45k-q8"],
                         [one.name for one in parse(doubled, CARD)])


if __name__ == "__main__":
    unittest.main()
