"""The preset file the router reads, as text.

Projecting outward is total: everything here has already been decided, and this only
writes it down. The one thing it can refuse is a file that would serve one of its own
sections and silently drop another -- see `preset`.

The format is the reference file's: `version = 1` before the first section, `[*]` for
what every model shares, one section per profile after it, `model` first inside a
section and the rest in alphabetical order, values unquoted, `;` starting a comment.
"""

from collections.abc import Mapping, Sequence
from dataclasses import dataclass

from .config import Config, ConfigError, Model, Value
from .machine import Machine, SystemMemory, system_memory, threads
from .name import Profile
from .place import (DRAFT_LOOKAHEAD, NO_TENSOR, Among, ExpertsOnCpu, Layout, Settings,
                    device_name, endpoints, holds, micro_batch, runs_apart_by_override)
from .rpc import written
from .units import Mib

HEADER = """; Generated by calibrate on this machine. Do not edit: the next run overwrites it.
;
; [*] is what this machine is and what every model runs with. Every other section is one
; way to run one model, and its name says which: the window in thousands of tokens, then
; what that way gives up -- -q4 for a coarser attention cache, -nomtp where a prediction
; head the file carries does not run, -2gpu for two of this machine's cards, and -rpc
; where it needs the card of another machine, lent through that machine's worker.
;
; The windows and the offloads are not preferences. They were computed against this
; card, to leave it about as much free memory as the settings file asks for.
;
; Every section opens with the video memory that profile holds once it is loaded. The
; router does not read it -- it is a comment. `vram` does: it is how that tool knows
; whether a model fits right now and what would have to be closed for it to fit."""

# The label `vram` finds a requirement by. Spelled loudly and in full because the line
# is the one thing in this file a person is meant to read rather than the router.
REQUIRED = "VRAM REQUIRED"

# Every layer on the card. A dense model is served whole or not at all, and a mixture
# moves experts with n-cpu-moe rather than by keeping layers off the card, so this never
# varies. 99 is how llama.cpp spells "all of them".
GPU_LAYERS = 99

# What llama.cpp calls the memory a server may hold cached prompts in.
CACHE = "cache-ram"


@dataclass(frozen=True)
class Placed:
    """One model with the profiles this card settled on. Empty where nothing fits.

    resident is what its heaviest profile keeps in system memory: nothing for a dense
    model that sits on the card whole, the offloaded experts for a mixture. The prompt
    cache is sized around it.
    """

    model: Model
    profiles: tuple[Profile, ...]
    resident: Mib


def preset(config: Config, machine: Machine, memory: SystemMemory,
           placed: Sequence[Placed]) -> str:
    """The whole preset file.

    A section name is what the router serves a model under, so two sections of one name
    are a file that serves one of them and drops the other without a word. Names are
    unique within a model by construction; across models they are not, since a model may
    be keyed anything at all -- `qwen3.8-45k` is a legal key, and it collides with a
    profile of `qwen3.8`. Here is where every name is visible at once, so here is where
    that is refused.
    """
    sections: dict[str, tuple[Placed, Settings]] = {}
    for one in placed:
        for profile in one.profiles:
            if profile.name in sections:
                raise ConfigError(f"duplicate section: {profile.name}")
            sections[profile.name] = (one, profile.settings)

    blocks = [_block("*", (), _shared(config, machine, memory))]
    blocks += [_block(name, _needs(settings), _section(config, machine, one, settings))
               for name, (one, settings) in sorted(sections.items())]

    return "\n\n".join([HEADER, "version = 1", *blocks]) + "\n"


def _shared(config: Config, machine: Machine,
            memory: SystemMemory) -> Mapping[str, Value]:
    """What every model runs with: this machine's numbers, then the file's own word.

    The machine's numbers come first so that a person who writes one down by hand wins.
    A hand-set thread count is a judgement about this machine that the reading cannot
    make -- the reading knows how many fast cores there are, not what else is using them.
    """
    keys: dict[str, Value] = {
        CACHE: memory.cache,
        "threads": threads(machine.cores),
        "threads-batch": threads(machine.cores),
        # Only reached by a model with no profile of its own, which is placed by the
        # loader rather than by us; this is the reserve it should place against.
        "fit-target": config.reserve,
    }
    keys.update(config.shared)
    return keys


def _section(config: Config, machine: Machine, placed: Placed,
             settings: Settings) -> Mapping[str, Value]:
    """One profile: where the file is, how it is placed, and what its vendor asked for.

    The placement is written out in full rather than left to be inherited from [*].
    A section says how it runs, and editing the shared block should not silently move a
    window that was computed for this card.

    The prompt cache is written here too, and it is this model's own: the router holds
    one model at a time, so what is left for prefixes is what this model's weights do
    not keep, and a heavier model elsewhere in the file is not its business.
    """
    keys: dict[str, Value] = {
        "model": str(placed.model.path),
        "ctx-size": settings.ctx,
        # The placement is already decided; the loader must not decide it again.
        "fit": "off",
        "gpu-layers": GPU_LAYERS,
        "cache-type-k": settings.cache.value,
        "cache-type-v": settings.cache.value,
    }

    if isinstance(settings.placement, ExpertsOnCpu):
        keys["n-cpu-moe"] = settings.placement.layers

    if settings.head:
        keys["spec-type"] = "draft-mtp"
        keys["spec-draft-n-max"] = DRAFT_LOOKAHEAD
        # The head is one more layer of the same conversation, and its history is
        # charged at the profile's precision. Allocating it at another would spend
        # memory the placement never counted.
        keys["spec-draft-type-k"] = settings.cache.value
        keys["spec-draft-type-v"] = settings.cache.value

    keys.update(_cache(config, machine, placed))
    keys.update(_layout(config, settings.layout))
    keys.update(placed.model.vendor)
    return keys


def _cache(config: Config, machine: Machine, placed: Placed) -> Mapping[str, Value]:
    """What this model leaves for cached prompts, where the file has not said.

    The router holds one model at a time, so what is left is what this model's own
    weights do not keep in system memory, and a heavier model elsewhere in the preset
    is none of its business. A size written into the shared block is a person's
    judgement about the whole machine and stands for every model, this one included.
    """
    if CACHE in config.shared:
        return {}

    return {CACHE: system_memory(config.cache_ram, machine, placed.resident).cache}


def _layout(config: Config, layout: Layout) -> Mapping[str, Value]:
    """Where the layers go and the micro-batch they run at, where either is not what
    [*] already says.

    A machine's only card at the file's own micro-batch adds nothing: the shared block
    already runs it that way, and a section repeating it would be a machine with one card
    described differently for no difference. One card of several is named and not split.
    """
    keys: dict[str, Value] = {}
    if layout.halvings > 0:
        keys["ubatch-size"] = micro_batch(config.runtime.ubatch, layout.halvings)

    if len(layout.devices) == 1:
        match layout.among:
            case Among.ONE:
                return keys
            case Among.SEVERAL:
                keys["device"] = device_name(layout.devices.first)
                keys["split-mode"] = "none"
                return keys

    keys["device"] = ",".join(device_name(one) for one in layout.devices)
    keys["split-mode"] = "layer"
    keys["tensor-split"] = ",".join(str(count) for count in layout.layers)

    reached = endpoints(layout)
    if reached:
        keys["rpc"] = ",".join(written(one) for one in reached)
    if runs_apart_by_override(layout):
        keys["override-tensor"] = f"{NO_TENSOR}={device_name(layout.devices.first)}"

    return keys


def _needs(settings: Settings) -> tuple[str, ...]:
    """What this profile holds on each device, for `vram` to read back.

    A comment rather than a key: the router is told how to run a model, not what it will
    cost, and a key it does not know is a key it could one day refuse. It sits in the
    section it is about rather than in a table at the head of the file, because a number
    kept away from what it describes goes stale with nobody noticing.
    """
    held = holds(settings)
    if len(held) == 1 and settings.layout.among is Among.ONE:
        return (f"{REQUIRED}: {held.first} MiB of video memory, "
                f"held from the moment this profile loads",)

    each = ", ".join(f"{amount} MiB on {device_name(device)}"
                     for device, amount in zip(settings.layout.devices, held))
    return (f"{REQUIRED}: {each}, held from the moment this profile loads",)


def _block(name: str, notes: Sequence[str], keys: Mapping[str, Value]) -> str:
    """One section. `model` first because it says which file the rest is about."""
    first = [f"model = {_text(keys['model'])}"] if "model" in keys else []
    rest = [f"{key} = {_text(keys[key])}"
            for key in sorted(keys) if key != "model"]

    return "\n".join([f"[{name}]", *[f"; {note}" for note in notes], *first, *rest])


def _text(value: Value) -> str:
    """A value as the router reads it: unquoted, and a switch spelled out."""
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)
